---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: summer-service
  namespace: spring-cloud
  labels:
    app: summer-service
spec:
  serviceName: "summer-service-svc"
  replicas: 2
  selector:
    matchLabels:
      app: summer-service
  template:
    metadata:
      labels:
        app: summer-service
    spec:
      containers:
      - name: summer-service
        image: altaira/client-summer:a0d96a9d83434a6f79ce6f727d033a17e7dffe70
