server:
  port: 8761

spring:
  application:
    name: service-discovery

eureka:
  instance:
    hostname: service-discovery
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url: 
      defaultZone: service-discovery-0.service-discovery-svc.spring-cloud.svc.cluster.local:8761,service-discovery-1.service-discovery-svc.spring-cloud.svc.cluster.local:8761,service-discovery-0.service-discovery-svc.spring-cloud.svc.cluster.local:8761/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
  replica:
    fetch-interval-seconds: 5
    register-with-eureka: true