
server:
  port: 8761

spring:
  application:
    name: discovery
  config:
    uri: http://config-server-svc:8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://service-discovery-svc:8080/eureka/