---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: service-discovery
  namespace: spring-cloud
  labels:
    app: service-discovery
spec:
  serviceName: "service-discovery-svc"
  replicas: 2
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
      - name: service-discovery
        image: altaira/service-discovery:4f5dab08be64231e39dda57de7271ea088162cbd
