---
apiVersion: v1
kind: Service
metadata:
  name: service-discovery-svc
  namespace: spring-cloud
spec:
  selector:
    app: service-discovery
  ports:
  - port: 8761
    protocol: TCP
  clusterIP: None
