server:
  port: 8030

spring:
  profiles:
    active: real
  application:
    name: spring-service
  cloud:
    config:
      uri: http://config-server-0.config-server-svc.spring-cloud.svc.cluster.local:8888,http://config-server-0.config-server-svc.spring-cloud.svc.cluster.local:8888
  config:
    import: "optional:configserver:"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-discovery-0.service-discovery-svc.spring-cloud.svc.cluster.local:8761/eureka,http://service-discovery-1.service-discovery-svc.spring-cloud.svc.cluster.local:8761/eureka
