server:
  port: 8030

spring:
  application:
    name: spring-service
  cloud:
    config:
      uri: http://config-server-svc.spring-cloud.svc.cluster.local:8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-discovery-svc.spring-cloud.svc.cluster.local:8080
