server:
  port: 8030

spring:
  application:
    name: spring-service
  config:
    import: configserver:http://config-server-svc.spring-cloud.svc.cluster.local:8080
  #profiles:
  #    active: dev

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-discovery-svc.spring-cloud.svc.cluster.local:8080
