server:
  port: 8030

spring:
  application:
    name: spring-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    discovery:
      locator:
        enabled: true
    kubernetes:
      loadbalancer:
        enabled: true
      enabled: true
    config:
      uri: http://config-server-svc.spring-cloud.svc.cluster.local:8080
  config:
    import: "optional:configserver:"

eureka:
  instance:
    preferIpAddress: false
    hostname: spring-service.spring-cloud.svc.cluster.local
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-discovery-0.service-discovery-svc.spring-cloud.svc.cluster.local:8761/eureka,http://service-discovery-1.service-discovery-svc.spring-cloud.svc.cluster.local:8761/eureka
