server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalutZone: http://service-discovery-svc:8080/eureka/

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: spring-service
          uri: lb://SPRING-SERVICE
          predicates:
            - Path=/spring-service/**
        - id: flask-service
          uri: lb://FLASK-SERVICE
          predicates:
            - Path=/flask-service/**
        - id: go-service
          uri: lb://GO-SERVICE
          predicates:
            - Path=/go-service/**
  config:
    uri: http://config-server-svc:8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, gateway