server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery-svc:8080/eureka/
    enabled: true

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: spring-service
          uri: lb://spring-service
          predicates:
            - Path=/spring-service/**
        - id: summer-service
          uri: lb://SUMMER-SERVICE
          predicates:
            - Path=/flask-service/**
        - id: go-service
          uri: lb://GO-SERVICE
          predicates:
            - Path=/go-service/**
  config:
    import: "optional:configserver:http://config-server-svc:8080"

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, gateway