---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spring-service
  namespace: spring-cloud
  labels:
    app: spring-service
spec:
  serviceName: "spring-service-svc"
  replicas: 2
  selector:
    matchLabels:
      app: spring-service
  template:
    metadata:
      labels:
        app: spring-service
    spec:
      containers:
      - name: spring-service
        image: altaira/client-springboot:96097bbc79810e884350366dbe699cde4a21b2a5
