---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: config-server
  namespace: spring-cloud
  labels:
    app: config-server
spec:
  serviceName: "config-server-svc"
  replicas: 2
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: altaira/config-server
