---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api-gateway
  namespace: spring-cloud
  labels:
    app: api-gateway
spec:
  serviceName: "api-gateway-svc"
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: altaira/api-gateway:d21b947d090081892df93272210c0240d766ce4d
